package com.example.pet.infrastructure.web;

import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;

/**
 * Schema record for OpenAPI documentation of validation error responses. This record describes the
 * structure of error responses returned by GlobalExceptionHandler when validation fails. It
 * extends the standard RFC 7807 Problem Details format with an additional 'errors' field
 * containing detailed validation error information.
 *
 * <p>Note: This record is used only for API documentation purposes and is never instantiated at
 * runtime. Actual error responses are generated by GlobalExceptionHandler using Spring's
 * ProblemDetail with dynamic properties.
 */
@Schema(description = "RFC 7807 Problem Detail response with validation error details")
public record ValidationErrorResponse(
        @Schema(description = "URI reference identifying the problem type", example = "about:blank")
                String type,
        @Schema(
                        description = "Short, human-readable summary of the problem",
                        example = "Bad Request")
                String title,
        @Schema(description = "HTTP status code", example = "400") int status,
        @Schema(
                        description = "Human-readable explanation specific to this occurrence",
                        example = "Validation failed for one or more fields")
                String detail,
        @Schema(
                        description =
                                "URI reference identifying the specific occurrence of the problem",
                        nullable = true)
                String instance,
        @Schema(
                        description = "List of field-level validation errors",
                        requiredMode = Schema.RequiredMode.REQUIRED)
                List<ValidationError> errors) {

    /** Represents a single field validation error. */
    @Schema(description = "Details of a single field validation error")
    public record ValidationError(
            @Schema(
                            description = "Name of the field that failed validation",
                            example = "name",
                            requiredMode = Schema.RequiredMode.REQUIRED)
                    String field,
            @Schema(
                            description = "The value that was rejected during validation",
                            example = "null",
                            nullable = true)
                    Object rejectedValue,
            @Schema(
                            description = "Human-readable validation error message",
                            example = "must not be blank",
                            requiredMode = Schema.RequiredMode.REQUIRED)
                    String message) {}
}
